### ISSUE TITLE
Apply alert filtering to alerts based on `k8up_*` metrics

### ISSUE THREAD

**Issue by simu** [projectsyn/component-backup-k8up#8]
## Context

Currently the alert filtering rules are only applied to the alert for metric `baas_backup_restic_last_errors`. However, the component also configures a number of alerts for `k8up_*` metrics.

To improve consistency, the alert filtering rules should also be applied to the alerts based on `k8up_*` metrics.

Note that the namespace for the actual backup is exposed as label `exported_namespace` for the `k8up_*` metrics, while label `namespace` always refers to the namespace in which K8up runs.

## Alternatives

The alternative is to leave the setup as is, which will lead to inconsistent alerting.

**Comment by Kidswiss** [comment]
@simu is this still relevant? The component underwent quite a lot of changes since you've opened this issue.

**Comment by simu** [comment]
Looks like parameter `alert_rule_filters` isn't used at all anymore in recent component versions. Not sure if there's a replacement mechanism which can be used to ignore K8up alerts for certain namespaces or not, but in its current form this issue is not relevant anymore.

Please note that the VSHN-internal global defaults still sets this parameter, so it might make sense to implement something like it again.

**Comment by Kidswiss** [comment]
Thanks for the feedback! I'm closing this issue. If any need for this feature would arise again, we can open a new one.
